name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
      
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.3.0

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
